format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'rosepinemoon'

[character]
format = '$symbol '
success_symbol = '[¿](green)'
error_symbol = '[¿](red)'
vimcmd_symbol = '[¿](gray)'
vimcmd_replace_one_symbol = '[¿](yellow)'
vimcmd_replace_symbol = '[¿](yellow)'
vimcmd_visual_symbol = '[¿](purple)'

[directory]
style = 'bold fg:fg'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '¿/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '¿ '
'Downloads' = '¿ '
'Music' = '¿ '
'Pictures' = '¿ '

[git_branch]
style = 'fg:green'
symbol = '¿ '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[fill]
symbol = ' '

[python]
style = 'fg:#387eb9'
symbol = '¿ '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
style = 'fg:#00007d'
symbol = '¿ '

[nodejs]
style = 'fg:#8bc500'
symbol = '¿ '

[golang]
style = 'fg:#6ad7e5'
symbol = '¿ '

[haskell]
style = 'fg:#5e5086'
symbol = '¿ '

[rust]
style = 'fg:#e43717'
symbol = '¿ '

[ruby]
style = 'fg:#af0f00'
symbol = '¿ '

[package]
symbol = '¿ '

[aws]
symbol = '¿ '
style = 'fg:#ff9900'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = '¿ '
style = 'fg:#099cec'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = '¿ '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[palettes.gruvboxlight]
black=    '#ebdbb2'
red=      '#cc241d'
green=    '#98971a'
yellow=   '#d79921'
blue=     '#458588'
white=    '#282828'
orange=   '#d65d0e'
purple=   '#b16286'
gray=     '#bdae93'

[palettes.gruvboxdark]
black=    '#3c3836'
red=      '#cc241d'
green=    '#98971a'
yellow=   '#d79921'
blue=     '#458588'
white=    '#fbf1c7'
orange=   '#d65d0e'
purple=   '#b16286'
gray=     '#665c54'

[palettes.rosepinedawn]
black=    '#575279'
red=      '#b4637a'
green=    '#56949f'
yellow=   '#ea9d34'
blue=     '#286983'
white=    '#fffaf3'
orange=   '#d7827e'
purple=   '#907aa9'
gray=     '#9893a5'

[palettes.rosepinemoon]
black=    '#2a273f'
white=    '#e0def4'
red=      '#eb6f92'
green=    '#9ccfd8'
yellow=   '#f6c177'
blue=     '#3e8fb0'
orange=   '#ea9a97'
purple=   '#907aa9'
gray=     '#9893a5'

[palettes.everforestlightsoft]
black=    '#5c6a72'
red=      '#f85552'
green=    '#8da101'
yellow=   '#dfa000'
blue=     '#3a94c5'
white=    '#d8d3ba'
orange=   '#e69875'
purple=   '#d699b6'
gray=     '#7a8478'

[palettes.everforestdarksoft]
black=    '#4d5960'
white=    '#d3c6aa'
red=      '#e67e80'
green=    '#a7c080'
yellow=   '#dbbc7f'
blue=     '#7fbbb3'
orange=   '#e69875'
purple=   '#d699b6'
gray=     '#7a8478'

[palettes.nord]
blue = '#81A1C1'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.nordlight]
blue = '#81A1C1'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'
