#!/bin/sh

export PREFERRED_FONT="Liga SFMono Nerd Font Mono"
export PREFERRED_FONT_SIZE=10
export PREFERRED_COLORSCHEME="gruvbox" # everforest, rose-pine, gruvbox, everblush, nord, catppuccin
export TRANSPARENT=false
