#!/bin/sh

# API endpoint for sunrise and sunset times
API_URL="https://api.sunrisesunset.io/json?lat=-7.17520&lng=112.63382&time_format=24"

# Fetch the sunrise and sunset times from the API
response=$(curl -s $API_URL)

# Extract sunrise and sunset times
sunrise=$(echo $response | jq -r '.results.sunrise')
sunset=$(echo $response | jq -r '.results.sunset')

# Get the current hour
current_time=$(date +'%H:%M:%S')

time_to_seconds() {
  local time=$1
  echo $(date -d "1970-01-01 $time UTC" +%s)
}

# Convert sunrise, sunset, and current time to seconds since midnight
sunrise_seconds=$(time_to_seconds "$sunrise")
sunset_seconds=$(time_to_seconds "$sunset")
current_seconds=$(time_to_seconds "$current_time")

# Get current theme
current=$(gsettings get org.gnome.desktop.interface color-scheme | tr -d "'")
current_color=$(awk -F'"' '/vim\.cmd\.colorscheme/ { print $2 }' ~/.config/nvim/lua/plugins/colorscheme.lua)
echo "current colorscheme is $current_color"

# set variables for each colorschemes
source ~/.scripts/customization
namelight=""
namedark=""
echo "the preferred colorscheme is $PREFERRED_COLORSCHEME"
if [[ $PREFERRED_COLORSCHEME == "everforest" ]]; then
  namelight="-light-soft"
  namedark="-dark-soft"
elif [[ $PREFERRED_COLORSCHEME == "rose-pine" ]]; then
  namelight="-dawn"
  namedark="-moon"
elif [[ $PREFERRED_COLORSCHEME == "gruvbox" ]]; then
  namelight="-light"
  namedark="-dark"
elif [[ $PREFERRED_COLORSCHEME == "nord" ]]; then
  namelight="-light"
  namedark="-dark"
fi


echo "the variables are $PREFERRED_COLORSCHEME $namelight $namedark"

# function to set things to light
set_light() {
  if [[ $current == "prefer-light" && "$current_color" == "$PREFERRED_COLORSCHEME" ]]; then
    echo "already light"
  else
    # ghostty
    sed -i "s|^\( *theme *= *\)dark:[^,]*,light:[^ ]*|\1dark:${PREFERRED_COLORSCHEME}${namedark},light:${PREFERRED_COLORSCHEME}${namelight}|" ~/.config/ghostty/config
    # kitty
    cat ~/.config/kitty/${PREFERRED_COLORSCHEME}${namelight}.auto.conf > ~/.config/kitty/light-theme.auto.conf
    cat ~/.config/kitty/${PREFERRED_COLORSCHEME}${namedark}.auto.conf > ~/.config/kitty/dark-theme.auto.conf
    # bat
    sed -i "s/^--theme-light=\".*\"/--theme-light=\"${PREFERRED_COLORSCHEME}${namelight}\"/" ~/.config/bat/config
    sed -i "s/^--theme-dark=\".*\"/--theme-dark=\"${PREFERRED_COLORSCHEME}${namedark}\"/" ~/.config/bat/config
    # waybar
    cat ~/.config/waybar/${PREFERRED_COLORSCHEME}${namelight}.waybar.css > ~/.config/waybar/style-light.css
    cat ~/.config/waybar/${PREFERRED_COLORSCHEME}${namedark}.waybar.css > ~/.config/waybar/style-dark.css
    # tmux
    sed -i "s|source ~/.tmux/.*\.tmux.conf|source ~/.tmux/${PREFERRED_COLORSCHEME}${namelight}.tmux.conf|" ~/.config/tmux/tmux.conf
    tmux source-file ~/.config/tmux/tmux.conf
    # nvim
    sed -i '55s/dark/light/g' ~/.config/nvim/lua/plugins/colorscheme.lua
    sed -i "s/vim\.cmd\.colorscheme(\".*\")/vim.cmd.colorscheme(\"$PREFERRED_COLORSCHEME\")/" ~/.config/nvim/lua/plugins/colorscheme.lua
    # vim

    # yazi
    # waypaper
    sed -i -E "s|(folder = ~/wallpapers/)[^/]+/[^/]+|\1$PREFERRED_COLORSCHEME/${namelight:1}|" ~/.config/waypaper/config.ini
    waypaper --random
    # rofi
    sed -i "s|@import \"~/.config/[^/]*/[^.]*\.rasi\"|@import \"~/.config/rofi/$PREFERRED_COLORSCHEME/${namelight:1}.rasi\"|" ~/.config/rofi/config.rasi
    # hyprland
    sed -i "s|source = ~/.config/hypr/colors/.*\.conf|source = ~/.config/hypr/colors/${PREFERRED_COLORSCHEME}${namelight}.conf|" ~/.config/hypr/hyprland.conf
    # starship
    sed -i "s|palette = '.*'|palette = '${PREFERRED_COLORSCHEME//-/}${namelight//-/}'|" ~/.config/starship.toml
    # swaync
    cat ~/.config/swaync/${PREFERRED_COLORSCHEME}${namelight}.swaync.css > ~/.config/swaync/style-light.css
    cat ~/.config/swaync/${PREFERRED_COLORSCHEME}${namedark}.swaync.css > ~/.config/swaync/style-dark.css
    cat ~/.config/swaync/style-light.css > ~/.config/swaync/style.css
    swaync-client -rs
    # hyprlock find random wall in the directory
    WALL_DIR="$HOME/wallpapers/$PREFERRED_COLORSCHEME/${namelight:1}"
    random_file=$(find "$WALL_DIR" -type f | shuf -n 1)
    escaped_home=$(printf '%s' "$HOME" | sed 's/[\/&]/\\&/g')
    escaped_random_file=$(printf '%s' "$random_file" | sed 's/[\/&]/\\&/g')
    sed -i "s|^\( *path *= *\).*|\1$escaped_random_file|" ~/.config/hypr/hyprlock.conf
    # le script
    sed -i "s|--preview 'bat --theme=\"[^\"]*\"|--preview 'bat --theme=\"${PREFERRED_COLORSCHEME}${namelight}\"|g" ~/.scripts/fzf_listoldfiles.sh
    # GTK
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
    # font & transparency
    set_font
    set_transparency
  fi
}

# function to set things to dark
set_dark() {
  # hyprpaper
  if [[ $current == "prefer-dark" && "$current_color" == "$PREFERRED_COLORSCHEME" ]]; then
    echo "already dark"
  else
    # ghostty
    sed -i "s|^\( *theme *= *\)dark:[^,]*,light:[^ ]*|\1dark:${PREFERRED_COLORSCHEME}${namedark},light:${PREFERRED_COLORSCHEME}${namelight}|" ~/.config/ghostty/config
    # kitty
    cat ~/.config/kitty/${PREFERRED_COLORSCHEME}${namelight}.auto.conf > ~/.config/kitty/light-theme.auto.conf
    cat ~/.config/kitty/${PREFERRED_COLORSCHEME}${namedark}.auto.conf > ~/.config/kitty/dark-theme.auto.conf
    # bat
    sed -i "s/^--theme-light=\".*\"/--theme-light=\"${PREFERRED_COLORSCHEME}${namelight}\"/" ~/.config/bat/config
    sed -i "s/^--theme-dark=\".*\"/--theme-dark=\"${PREFERRED_COLORSCHEME}${namedark}\"/" ~/.config/bat/config
    # waybar
    cat ~/.config/waybar/${PREFERRED_COLORSCHEME}${namelight}.waybar.css > ~/.config/waybar/style-light.css
    cat ~/.config/waybar/${PREFERRED_COLORSCHEME}${namedark}.waybar.css > ~/.config/waybar/style-dark.css
    # tmux
    sed -i "s|source ~/.tmux/.*\.tmux.conf|source ~/.tmux/${PREFERRED_COLORSCHEME}${namedark}.tmux.conf|" ~/.config/tmux/tmux.conf
    tmux source-file ~/.config/tmux/tmux.conf
    # nvim
    sed -i '55s/light/dark/g' ~/.config/nvim/lua/plugins/colorscheme.lua
    sed -i "s/vim\.cmd\.colorscheme(\".*\")/vim.cmd.colorscheme(\"$PREFERRED_COLORSCHEME\")/" ~/.config/nvim/lua/plugins/colorscheme.lua
    # yazi
    # waypaper
    sed -i -E "s|(folder = ~/wallpapers/)[^/]+/[^/]+|\1$PREFERRED_COLORSCHEME/${namedark:1}|" ~/.config/waypaper/config.ini
    waypaper --random
    # rofi
    sed -i "s|@import \"~/.config/[^/]*/[^.]*\.rasi\"|@import \"~/.config/rofi/$PREFERRED_COLORSCHEME/${namedark:1}.rasi\"|" ~/.config/rofi/config.rasi
    # hyprland
    sed -i "s|source = ~/.config/hypr/colors/.*\.conf|source = ~/.config/hypr/colors/${PREFERRED_COLORSCHEME}${namedark}.conf|" ~/.config/hypr/hyprland.conf
    # starship
    sed -i "s|palette = '.*'|palette = '${PREFERRED_COLORSCHEME//-/}${namedark//-/}'|" ~/.config/starship.toml
    # swaync
    cat ~/.config/swaync/${PREFERRED_COLORSCHEME}${namelight}.swaync.css > ~/.config/swaync/style-light.css
    cat ~/.config/swaync/${PREFERRED_COLORSCHEME}${namedark}.swaync.css > ~/.config/swaync/style-dark.css
    cat ~/.config/swaync/style-dark.css > ~/.config/swaync/style.css
    swaync-client -rs
    # hyprlock find random wall in the directory
    WALL_DIR="$HOME/wallpapers/$PREFERRED_COLORSCHEME/${namedark:1}"
    random_file=$(find "$WALL_DIR" -type f | shuf -n 1)
    escaped_home=$(printf '%s' "$HOME" | sed 's/[\/&]/\\&/g')
    escaped_random_file=$(printf '%s' "$random_file" | sed 's/[\/&]/\\&/g')
    sed -i "s|^\( *path *= *\).*|\1$escaped_random_file|" ~/.config/hypr/hyprlock.conf
    # le script
    sed -i "s|--preview 'bat --theme=\"[^\"]*\"|--preview 'bat --theme=\"${PREFERRED_COLORSCHEME}${namedark}\"|g" ~/.scripts/fzf_listoldfiles.sh
    # GTK
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
    # font & transparency
    set_font
    set_transparency
  fi
}

# function to change fonts
set_font(){
  ESCAPED_FONT=$(printf '%s\n' "$PREFERRED_FONT" | sed 's/^["'\'']//;s/["'\'']$//')

  echo "changing ghostty fonts to $PREFERRED_FONT"
  # ghostty
  sed -i "s/^font-family *= *\".*\"/font-family = \"$ESCAPED_FONT\"/" ~/.config/ghostty/config
  sed -i "s/^font-size *= *[0-9]\+/font-size = $((PREFERRED_FONT_SIZE -1))/" ~/.config/ghostty/config

  echo "changing swaync fonts to $PREFERRED_FONT"
  # swaync light
  sed -i "s/^\( *font-family: *\)[^;]*;/\1\"$ESCAPED_FONT\";/" ~/.config/swaync/style-light.css
  sed -i "s/^\( *font-size: *\)[^;]*;/\1$PREFERRED_FONT_SIZE;/" ~/.config/swaync/style-light.css
  # swaync dark
  sed -i "s/^\( *font-family: *\)[^;]*;/\1\"$ESCAPED_FONT\";/" ~/.config/swaync/style-dark.css
  sed -i "s/^\( *font-size: *\)[^;]*;/\1$PREFERRED_FONT_SIZE;/" ~/.config/swaync/style-dark.css
  # swaync current
  sed -i "s/^\( *font-family: *\)[^;]*;/\1\"$ESCAPED_FONT\";/" ~/.config/swaync/style.css
  sed -i "s/^\( *font-size: *\)[^;]*;/\1$PREFERRED_FONT_SIZE;/" ~/.config/swaync/style.css
  swaync-client -rs

  echo "changing waybar fonts to $PREFERRED_FONT"
  # waybar
  # waybar light
  sed -i "s/^\( *font-family: *\)[^;]*;/\1\"$ESCAPED_FONT\";/" ~/.config/waybar/style-light.css
  sed -i "s/^\( *font-size: *\)[^;]*;/\1$PREFERRED_FONT_SIZE;/" ~/.config/waybar/style-light.css
  # waybar dark
  sed -i "s/^\( *font-family: *\)[^;]*;/\1\"$ESCAPED_FONT\";/" ~/.config/waybar/style-dark.css
  sed -i "s/^\( *font-size: *\)[^;]*;/\1$PREFERRED_FONT_SIZE;/" ~/.config/waybar/style-dark.css
  pkill -SIGUSR2 waybar

  echo "changing rofi fonts to $PREFERRED_FONT"
  sed -i "s/^\(\s*font: *\"\)[^\"]*\( *[0-9]\+\)\";/\1${ESCAPED_FONT} ${PREFERRED_FONT_SIZE}\";/" ~/.config/rofi/config.rasi
}

set_transparency() {
  FILE="$HOME/.config/nvim/lua/plugins/transparent.lua"
  BACKUP="$FILE.old"

  if [[ $TRANSPARENT == false ]]; then
    echo "disabling transparency..."
    # ghostty
    sed -i \
      -e 's/^\s*\(background-opacity\s*=.*\)/# \1/' \
      -e 's/^\s*\(background-blur\s*=.*\)/# \1/' \
      -e 's/^\s*\(background-blur-radius\s*=.*\)/# \1/' \
      -e 's/^\s*\(alpha-blending\s*=.*\)/# \1/' \
      "$HOME/.config/ghostty/config"

    # nvim
    # Check if the file exists before renaming
    if [ -f "$FILE" ]; then
        mv "$FILE" "$BACKUP"
        echo "Renamed: $FILE → $BACKUP"
    else
        echo "File not found: $FILE"
    fi

    # lualine
    sed -i \
    -e "/require('transparent')/{
      /^[[:space:]]*--/!s/^\([[:space:]]*\)\(require('transparent').clear_prefix('lualine')\)/\1-- \2/
    }" \
    "$HOME/.config/nvim/lua/plugins/lualine.lua"

  else
    echo "enabling transparency..."
    # ghostty
    sed -i \
      -e 's/^\s*#\s*\(background-opacity\s*=.*\)/\1/' \
      -e 's/^\s*#\s*\(background-blur\s*=.*\)/\1/' \
      -e 's/^\s*#\s*\(background-blur-radius\s*=.*\)/\1/' \
      -e 's/^\s*#\s*\(alpha-blending\s*=.*\)/\1/' \
      "$HOME/.config/ghostty/config"
    # nvim

    # Check if the file exists before renaming
    if [ -f "$BACKUP" ]; then
        mv "$BACKUP" "$FILE"
        echo "Renamed: $BACKUP → $FILE"
    else
        echo "File not found: $BACKUP"
    fi

    # lualine
    sed -i \
      -e "s/^\([[:space:]]*\)--[[:space:]]*\(require('transparent').clear_prefix('lualine')\)/\1\2/" \
      "$HOME/.config/nvim/lua/plugins/lualine.lua"
  fi
}

if [ -z "$1" ]; then
  echo "Argument is empty"
else
  echo "Argument is: $1"
fi

if [ -n "$1" ] && [ "$1" = "manual" ]; then
  if [ "$current" = "prefer-dark" ]; then
    set_light
  else
    set_dark
  fi
else
  # Compare current time to sunrise and sunset times
  if (( current_seconds >= sunrise_seconds && current_seconds <= sunset_seconds )); then
    set_light
  else
    set_dark
  fi
fi
